CREATE DATABASE IF NOT EXISTS adminct CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE adminct;

CREATE TABLE IF NOT EXISTS users (
  id_users INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

